services:
  - type: web
    name: tinyorm-backend
    env: node
    buildCommand: npm install && npm run build --workspace server
    startCommand: npm start --workspace server
    envVars:
      - key: NODE_ENV
        value: production
