export type FilterOperator =
  | 'eq'
  | 'neq'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'in'
  | 'notIn'
  | 'contains'
  | 'startsWith'
  | 'endsWith'
  | 'isNull'
  | 'isNotNull';

export type WhereCondition<T> = {
  [K in keyof T]?:
    | T[K]
    | {
        eq?: T[K];
        neq?: T[K];
        gt?: T[K];
        gte?: T[K];
        lt?: T[K];
        lte?: T[K];
        in?: T[K][];
        notIn?: T[K][];
        contains?: string;
        startsWith?: string;
        endsWith?: string;
        isNull?: boolean;
        isNotNull?: boolean;
      };
} & {
  AND?: WhereCondition<T>[];
  OR?: WhereCondition<T>[];
  NOT?: WhereCondition<T>;
};

export type OrderByCondition<T> = {
  [K in keyof T]?: 'asc' | 'desc';
};

export interface FindManyArgs<T> {
  where?: WhereCondition<T>;
  orderBy?: OrderByCondition<T>;
  limit?: number;
  offset?: number;
  include?: Record<string, boolean>;
}

export interface FindUniqueArgs<T> {
  where: WhereCondition<T>;
  include?: Record<string, boolean>;
}

export interface CreateArgs<T> {
  data: Partial<T>; // Omit autogenerated keys in a strict implementation
}

export interface UpdateArgs<T> {
  where: WhereCondition<T>;
  data: Partial<T>;
}

export interface DeleteArgs<T> {
  where: WhereCondition<T>;
}
